sudo: false
language: node_js
env:
  CODECOV_TOKEN="967cc3b5-600b-4b03-a6b2-6939a817c70e"
node_js:
  - 8
  - 9
  - 10
# keep the npm cache to speed up installs
cache:
  directories:
    - "$HOME/.npm"
script:
  - npm run all
  - npm run build
after_success:
  - npx nyc report --reporter=lcov | npx codecov
  - npm run cov:check
